page with posts of subscribed categories
lambda-py/py_june pull request #127
Opened 2024-05-25 12:58 UTC by valfutz

2024-05-27 07:28 UTC, NykoEugen reviewed
Look's good for me. One thing should be done, a button for user subscribtions somwhere.

2024-05-28 16:52 UTC, acman requested changes
Nice job! Rename please all parts to something more clear like SubscriptionPost, subscription_post_list.html and so on

2024-05-28 16:52 UTC, acman commented on subscription/urls.py
> +        "posts-of-subcribed/",
lets it be only `posts`, it will be displayed as `subscription/posts`

2024-05-28 16:52 UTC, acman commented on subscription/views.py
> +class PostsOfSubscribedCategoriesView(LoginRequiredMixin, View):
```suggestion
class SubscriptionPostView(LoginRequiredMixin, View):
```

2024-05-31 15:35 UTC, acman approved these changes
👍

2024-05-31 15:35 UTC, merged