Pj 134 emptu comment
lambda-py/py_june pull request #24
Opened 2024-01-29 18:06 UTC by NykoEugen

Make some fix. Add validate func for comment reply (remove <blockquot> and check that str not empty) Now make notification that can't create empty comment or comment reply.

2024-01-29 19:21 UTC, acman requested changes
Looks ok. Add tests for `not_empty_comment` function and for post view with several cases

2024-01-29 19:21 UTC, acman commented on posts/views.py
> +        message = "An empty comment cannot be created"
```suggestion
        error_message = "An empty comment cannot be created"
```

2024-01-29 19:21 UTC, acman commented on posts/views.py
> +        message = "An empty comment cannot be created"
it is ok for now but all validation errors should be part of form.

2024-01-29 19:21 UTC, acman commented on core/utils/empty_comment.py
> +    # Регулярний вираз для пошуку всіх блоків <blockquote>...</blockquote>
add comments only in english

2024-01-29 19:25 UTC, NykoEugen commented on posts/views.py
> +        message = "An empty comment cannot be created"
How does it base in form, and how should it be render?

2024-01-29 21:49 UTC, NykoEugen commented
Have question, why error in form func cleaned_data, doesn't raise error wich place in if else block?

2024-01-30 09:53 UTC, acman commented on posts/views.py
> +        message = "An empty comment cannot be created"
all errors should be return as part of form message, but we have ckeditor, so I don't know how it works with it

2024-01-30 09:57 UTC, acman commented on comments/forms.py
> +        if not_empty_comment(content):
I think it would be clearer
```suggestion
        if is_empty_comment(content):
            raise forms.ValidationError(_("Empty comment"))
            
        return html_sanitizer(content)
```

2024-01-30 09:58 UTC, acman commented
Can't say what is problem on the fly, run tests in debug mode and debug. If there will be problems I will investigate it later

2024-02-01 08:33 UTC, NykoEugen commented
I tried make debug, but didn't see that cod except error, but cod work corectly.

2024-02-01 15:32 UTC, acman approved these changes
Ok, lets move forward. We can come back to it later

2024-02-01 15:33 UTC, merged