pj-139-rework-post-edit-view add js and rebuild a post-form
lambda-py/py_june pull request #35
Opened 2024-02-01 19:53 UTC by NykoEugen

Rebuild post form for using creditor for editing post content. Add JS for display this form by button click. The edit form display when get and post. But have problem with saving editform. Have this error:
![image](https://github.com/lambda-py/py_june/assets/121561222/58e67041-b886-4a65-8819-1a59d61e2da9)

No idea how does it fix

2024-02-02 07:18 UTC, NykoEugen commented
I thin this error is because ckeditor to add many tags (for example enstead of space add &nbsp;). Thats why we cant edit this form corectly

2024-02-02 07:35 UTC, NykoEugen commented
I found my problem. The problem is in an instance=post. There are send all html cod ckeditor

2024-02-02 07:49 UTC, NykoEugen commented
Fix it) Now edit post works on one page

2024-02-02 15:43 UTC, acman requested changes
Looks fine, but there are a lot of forms there, so all cases with forms should be tested accurately. There are no guarantees that everything works as expected

2024-02-02 15:43 UTC, acman commented on posts/views.py
> +        print(form)
remove `print`.

2024-02-02 15:43 UTC, acman commented on posts/views.py
> +                # "edit_post_form": edit_post_form,
I think it could be removed

2024-02-02 16:17 UTC, NykoEugen commented
> Looks fine, but there are a lot of forms there, so all cases with forms should be tested accurately. There are no guarantees that everything works as expected

So how realize all this funktion in one view?

2024-02-05 15:28 UTC, acman commented
I think it is ok to have all that forms in one view, just write tests for processings all cases and we will see if there are any conflicts

2024-02-06 13:09 UTC, NykoEugen commented
Works fine but how to hide delete form, don't know. Tests in progress

2024-02-07 15:12 UTC, acman approved these changes
Looks really nice! I will try to test all forms

2024-02-07 15:13 UTC, merged