pj-106/107 add notification messages, some update views code, some im…
lambda-py/py_june pull request #72
Opened 2024-03-05 10:28 UTC by NykoEugen

…proves

2024-03-05 10:28 UTC, NykoEugen commented
tests fix later

2024-03-05 17:53 UTC, acman requested changes
Looks good! Needs some clarification.

2024-03-05 17:53 UTC, acman commented on static/js/category.js
> +document.addEventListener("DOMContentLoaded", function () {
I am not sure I understand what is purpose for it? Could be added some comments to clarify the code?

2024-03-05 17:53 UTC, acman commented on static/js/post.js
> +  console.log(messageBlock)
console logs should be removed

2024-03-05 17:58 UTC, NykoEugen commented on static/js/category.js
> +document.addEventListener("DOMContentLoaded", function () {
maybe it should be add in main JS. This is notification about some actions(create and limitation)

2024-03-05 18:10 UTC, acman commented
Don't see any comments in code, try to describe code and add some examples to be clear for other developers :) especially in JS :)

2024-03-05 18:10 UTC, acman commented
and there are some conflicts

2024-03-07 09:23 UTC, acman approved these changes
👍

2024-03-07 09:23 UTC, merged