Added possibility add links to profile
lambda-py/py_june pull request #89
Opened 2024-03-22 12:51 UTC by Nikita88575

![Screenshot 2024-03-22 at 14 22 39](https://github.com/lambda-py/py_june/assets/48783453/e02a0212-ef2a-4bdd-a409-934c4b917428)
![Screenshot 2024-03-22 at 14 23 25](https://github.com/lambda-py/py_june/assets/48783453/85560931-c9da-44a6-873e-883bd20f1948)
![Screenshot 2024-03-22 at 14 46 51](https://github.com/lambda-py/py_june/assets/48783453/07ae2065-1991-4d1f-8527-8fbf427436a3)

2024-03-22 13:02 UTC, Nikita88575 commented
Mobile version:
![Screenshot_20240322-150034.jpg](https://github.com/lambda-py/py_june/assets/48783453/6fcbae69-cdc7-4c27-a318-d2e6b1fcbaa3)

![Screenshot_20240322-145928.jpg](https://github.com/lambda-py/py_june/assets/48783453/7009c4e9-568a-4647-90cf-a3d0bd73d0e1)

2024-03-22 17:29 UTC, acman requested changes
Really good job! Look at https://docs.djangoproject.com/en/5.0/ref/forms/validation/#cleaning-a-specific-field-attribute.
Oh, not `validate_` that I had mentioned in PR before but `clean_` functions should be used

2024-03-22 17:29 UTC, acman commented on profiles/forms.py
> +    def github(self) -> str:
I think this function should be like `validate_github` and others. When is_valid() is called it will check all validate_ functions

2024-03-22 17:29 UTC, acman commented on profiles/forms.py
> +        if github == "":
```suggestion
        if not github_link:
```

2024-03-22 17:29 UTC, acman commented on profiles/forms.py
> +            return "Error"
I think there should be something like
```suggestion
            raise ValidationError('github url is not valid')
```

2024-03-22 17:29 UTC, acman commented on profiles/forms.py
> +            return "Error"
and the same for others

2024-03-22 17:29 UTC, acman commented on profiles/models.py
> +    user = models.ForeignKey(
I think there should be O2O because user should have only one profile

2024-03-22 17:29 UTC, acman commented on profiles/models.py
> +class Profile(models.Model):
I think we need something like SlugModel to show profile by link like py-june.dev/profiles/\<username\>/

2024-03-22 17:29 UTC, acman commented on profiles/tests.py
> +        print(response)
print statements should be deleted

2024-03-22 17:29 UTC, acman commented on profiles/views.py
> +        profile = get_object_or_404(Profile, user=self.request.user)
As I remember first value will be True or False, and second is profile
```suggestion
        _, profile = Profile.objects.get_or_create(user=self.request.user)
```

2024-03-22 17:29 UTC, acman commented on profiles/views.py
> +                )
Yeah, this could is redundant, if validate_ functions will be used, it will create errors like that

2024-03-22 17:29 UTC, acman commented on templates/profiles/profile.html
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet" type="text/css">
what is it for?

2024-03-22 17:29 UTC, acman commented on templates/profiles/profile.html
> +        {% if not profile.github_link and not profile.linkedin_link and not profile.instagram_link %}
I think it is too complex, just render links if they are in profile otherwise let `User Info` to be empty block

2024-03-22 17:45 UTC, Nikita88575 commented on profiles/forms.py
> +            return "Error"
raise ValidationError('github url is not valid') returns error on backend
![Screenshot 2024-03-22 at 19 44 17](https://github.com/lambda-py/py_june/assets/48783453/ca60517a-4d0e-4e62-911f-16c17a622091)

2024-03-22 17:52 UTC, Nikita88575 commented on profiles/models.py
> +class Profile(models.Model):
![Screenshot 2024-03-22 at 19 50 09](https://github.com/lambda-py/py_june/assets/48783453/8347475f-cb88-4756-a50e-af1836f9e6a1)
![Screenshot 2024-03-22 at 19 51 17](https://github.com/lambda-py/py_june/assets/48783453/d538f847-29cf-4f95-a981-19ab034bfab9)

2024-03-22 17:57 UTC, Nikita88575 commented on templates/profiles/profile.html
> +    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet" type="text/css">
<img width="241" alt="Screenshot 2024-03-22 at 19 56 58" src="https://github.com/lambda-py/py_june/assets/48783453/19ab0967-5d31-43d9-afd7-91351066f20f">

2024-03-22 18:01 UTC, Nikita88575 commented on profiles/models.py
> +    user = models.ForeignKey(
when a user visits a profile page, 1 record is created for him which will be updated in the future

2024-03-22 18:20 UTC, Nikita88575 commented on profiles/forms.py
> +    def github(self) -> str:
https://github.com/lambda-py/py_june/assets/48783453/b5e06627-e347-43ac-987b-3ea85d7b7336

2024-03-22 18:29 UTC, Nikita88575 commented on profiles/forms.py
> +    def github(self) -> str:
https://github.com/lambda-py/py_june/assets/48783453/edef5dd5-a082-4fc3-bd91-5ea385176ebc

2024-03-24 09:35 UTC, acman requested changes
I think there are some problems in saving objects, other staff  looks good

2024-03-24 09:35 UTC, acman commented on profiles/forms.py
> +    def clean(self) -> str:
looks great but it returns `dict`

2024-03-24 09:35 UTC, acman commented on profiles/models.py
> +class Profile(models.Model):
ok

2024-03-24 09:35 UTC, acman commented on profiles/models.py
> +    user = models.ForeignKey(
yes but if FK is used it means that multiple profiles could be for one user, it is not correct from design prospective

2024-03-24 09:35 UTC, acman commented on profiles/views.py
> +            user_profile.save()
some incorrect namings there
```suggestion
            user_profile = edit_profile_form.save(commit=False)
            user_links = edit_links_form.save(commit=False)
            user_profile.user = self.request.user
            user_profile.save()
            user_links.save()
```

2024-03-24 09:35 UTC, acman commented on templates/header.html
> +          <a href="{% url 'profile:profile' request.user.username %}">
I think it works without `request`

2024-03-24 09:38 UTC, acman commented on profiles/forms.py
> +    def github(self) -> str:
hm, there should be some tests written to understand why it behave so weird

2024-03-24 09:44 UTC, Nikita88575 commented on templates/header.html
> +          <a href="{% url 'profile:profile' request.user.username %}">
works, but if the user clicks the "My profile" button on another user's page, it won't take him back to his profile page

2024-03-24 10:00 UTC, acman commented on templates/header.html
> +          <a href="{% url 'profile:profile' request.user.username %}">
hm it is strange, probably because there several profiles created

2024-03-24 10:07 UTC, Nikita88575 commented on profiles/forms.py
> +    def clean(self) -> str:
But it works without problems

2024-03-24 10:12 UTC, Nikita88575 commented on templates/header.html
> +          <a href="{% url 'profile:profile' request.user.username %}">
it`s not strange, because in user variable we get the user whose page we are visiting:
```
def get(self, request: HttpRequest, profile: str) -> HttpResponse:
        user = get_object_or_404(ForumUser, username=profile)
```

2024-03-24 10:22 UTC, Nikita88575 commented on profiles/forms.py
> +    def clean(self) -> str:
it should be something like this ?:
`
if github and not github.startswith("https://github.com/"):
    self.add_error(
        "github_link",
        _("Invalid GitHub profile URL. Please use format: https://github.com/"),
    )
else:
    return github

if linkedin and not linkedin.startswith("https://www.linkedin.com/in/"):
    self.add_error(
        "linkedin_link",
        _(
            "Invalid Linkedin profile URL. Please use format: https://www.linkedin.com/in/"
        ),
    )
else:
    return linkedin

if instagram and not instagram.startswith("https://www.instagram.com/"):
    self.add_error(
        "instagram_link",
        _(
            "Invalid Instagram profile URL. Please use format: https://www.instagram.com/"
        ),
    )
else:
    return instagram`

2024-03-24 13:54 UTC, acman approved these changes
👍

2024-03-24 13:54 UTC, merged